# Generated by Django 5.1.5 on 2025-02-08 08:31

import django.db.models.deletion
import extensions.utils
import extensions.validators
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyOwnerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'نوع مالکیت شرکت',
                'verbose_name_plural': 'نوع مالکیت شرکت',
            },
        ),
        migrations.CreateModel(
            name='CompanySubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='موضوع فعالیت')),
            ],
            options={
                'verbose_name': 'موضوع فعالیت شرکت',
                'verbose_name_plural': 'موضوع فعالیت شرکت',
            },
        ),
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='نوع کمپانی')),
            ],
            options={
                'verbose_name': 'نوع شرکت',
                'verbose_name_plural': 'نوع شرکت',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'نوع مدرک شناسایی',
                'verbose_name_plural': 'نوع مدرک شناسایی',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('identifier', models.BigIntegerField(default=functools.partial(extensions.utils.generate_random_number, *(13,), **{}), verbose_name='شناسه فروشنده خارجی')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('document', models.FileField(blank=True, default=None, max_length=500, null=True, upload_to='overseas_supplyer/supplier', validators=[extensions.validators.validate_file_size, extensions.validators.validate_file_extension], verbose_name='انتخاب تصویر مدارک')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام/ First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی/ Last Name')),
                ('father_name', models.CharField(max_length=100, verbose_name='نام پدر')),
                ('mother_name', models.CharField(blank=True, default=None, max_length=100, verbose_name='نام مادر')),
                ('grandfather_name', models.CharField(blank=True, default=None, max_length=100, verbose_name='نام جد')),
                ('city', models.CharField(blank=True, default=None, max_length=50, verbose_name='شهر محل تولد')),
                ('gender', models.CharField(choices=[('mail', 'مرد'), ('fmail', 'زن')], max_length=5, verbose_name='جنسیت')),
                ('birthday', models.DateField(verbose_name='تاریخ تولد')),
                ('maried', models.CharField(choices=[('s', 'مجرد'), ('m', 'متاهل'), ('c', 'متارکه'), ('w', 'بیوه')], max_length=50, verbose_name='وضعیت تاهل')),
                ('personal_image', models.ImageField(blank=True, default=None, max_length=1000, upload_to='overseas_supplier/', verbose_name='تصویر پرسنلی')),
                ('document_number', models.CharField(max_length=100, verbose_name='شماره مدرک شناسایی')),
                ('issue_date', models.DateField(verbose_name='تاریخ صدور')),
                ('expire_date', models.DateField(verbose_name='تاریخ انقضا')),
            ],
            options={
                'verbose_name': 'شخص حقیقی',
                'verbose_name_plural': 'شخص حقیقی',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('identifier', models.BigIntegerField(default=functools.partial(extensions.utils.generate_random_number, *(13,), **{}), verbose_name='شناسه فروشنده خارجی')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('document', models.FileField(blank=True, default=None, max_length=500, null=True, upload_to='overseas_supplyer/supplier', validators=[extensions.validators.validate_file_size, extensions.validators.validate_file_extension], verbose_name='انتخاب تصویر مدارک')),
                ('name', models.CharField(max_length=100, verbose_name='نام فارسی شرکت خارجی')),
                ('en_name', models.CharField(max_length=100, verbose_name='نام لاتین شرکت خارجی')),
                ('register_number', models.PositiveIntegerField(verbose_name='شماره ثبت')),
                ('registered_date', models.DateField(verbose_name='تاریخ ثبت')),
                ('city', models.CharField(max_length=50, verbose_name='شهر')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('postal_code', models.PositiveIntegerField(blank=True, default=None, verbose_name='کد پستی')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تلفن')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country', to='dashboard.country', verbose_name='کشور')),
                ('registered_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.country', verbose_name='کشور محل ثبت')),
                ('registered_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_from', to='dashboard.country', verbose_name='تابعیت ثبتی شرکت')),
            ],
            options={
                'verbose_name': 'شرکت',
                'verbose_name_plural': 'شرکت\u200c',
            },
        ),
    ]
