# Generated by Django 5.1.5 on 2025-02-08 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('overseas_supplier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر مربوطه'),
        ),
        migrations.AddField(
            model_name='company',
            name='owner_type',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='overseas_supplier.companyownertype', verbose_name='نوع مالکیت'),
        ),
        migrations.AddField(
            model_name='company',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='overseas_supplier.companysubject', verbose_name='موضوع فعالیت شرکت'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='overseas_supplier.companytype', verbose_name='نوع شرکت'),
        ),
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.country', verbose_name='کشور محل تولد'),
        ),
        migrations.AddField(
            model_name='person',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overseas_supplier.documenttype', verbose_name='نوع مدرک شناسایی'),
        ),
        migrations.AddField(
            model_name='person',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='natinality_country', to='dashboard.country', verbose_name='ملیت'),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر مربوطه'),
        ),
    ]
