# Generated by Django 5.1.6 on 2025-02-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overseas_supplier', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='postal_code',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='کد پستی'),
        ),
    ]
