# Generated by Django 5.1.6 on 2025-02-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overseas_supplier', '0003_alter_company_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='تلفن'),
        ),
    ]
