# Generated by Django 5.1.6 on 2025-02-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overseas_supplier', '0004_alter_company_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='companytype',
            name='order',
            field=models.IntegerField(blank=True, default=0, verbose_name='مرتب سازی'),
        ),
    ]
