# Generated by Django 5.1.6 on 2025-02-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overseas_supplier', '0005_companytype_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyownertype',
            options={'ordering': ['order_by'], 'verbose_name': 'نوع مالکیت شرکت', 'verbose_name_plural': 'نوع مالکیت شرکت'},
        ),
        migrations.AlterModelOptions(
            name='companysubject',
            options={'ordering': ['order_by'], 'verbose_name': 'موضوع فعالیت شرکت', 'verbose_name_plural': 'موضوع فعالیت شرکت'},
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ['order_by'], 'verbose_name': 'نوع مدرک شناسایی', 'verbose_name_plural': 'نوع مدرک شناسایی'},
        ),
        migrations.AddField(
            model_name='companyownertype',
            name='order_by',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='مرتب سازی'),
        ),
        migrations.AddField(
            model_name='companysubject',
            name='order_by',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='مرتب سازی'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='order_by',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='مرتب سازی'),
        ),
    ]
