# Generated by Django 5.1.6 on 2025-02-20 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overseas_supplier', '0006_alter_companyownertype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyownertype',
            options={'ordering': ['order_by', 'title'], 'verbose_name': 'نوع مالکیت شرکت', 'verbose_name_plural': 'نوع مالکیت شرکت'},
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ['order_by', 'name'], 'verbose_name': 'نوع مدرک شناسایی', 'verbose_name_plural': 'نوع مدرک شناسایی'},
        ),
    ]
