# Generated by Django 5.1.6 on 2025-03-01 11:25

import extensions.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overseas_supplier', '0007_alter_companyownertype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-created_at'], 'verbose_name': 'شرکت', 'verbose_name_plural': 'شرکت\u200c'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-created_at'], 'verbose_name': 'شخص حقیقی', 'verbose_name_plural': 'شخص حقیقی'},
        ),
        migrations.AlterField(
            model_name='company',
            name='document',
            field=models.FileField(default=1, max_length=500, upload_to='overseas_supplyer/supplier', validators=[extensions.validators.validate_file_size, extensions.validators.validate_file_extension], verbose_name='انتخاب تصویر مدارک'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='document',
            field=models.FileField(default=1, max_length=500, upload_to='overseas_supplyer/supplier', validators=[extensions.validators.validate_file_size, extensions.validators.validate_file_extension], verbose_name='انتخاب تصویر مدارک'),
            preserve_default=False,
        ),
    ]
