# Generated by Django 5.1.6 on 2025-03-03 09:23

import extensions.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overseas_supplier', '0008_alter_company_options_alter_person_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='document',
            field=models.FileField(blank=True, default=None, max_length=500, null=True, upload_to='overseas_supplyer/supplier', validators=[extensions.validators.validate_file_size, extensions.validators.validate_file_extension], verbose_name='انتخاب تصویر مدارک'),
        ),
        migrations.AlterField(
            model_name='person',
            name='document',
            field=models.FileField(blank=True, default=None, max_length=500, null=True, upload_to='overseas_supplyer/supplier', validators=[extensions.validators.validate_file_size, extensions.validators.validate_file_extension], verbose_name='انتخاب تصویر مدارک'),
        ),
    ]
