# Generated by Django 5.1.6 on 2025-03-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overseas_supplier', '0009_alter_company_document_alter_person_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='document_flag',
            field=models.BooleanField(default=False, verbose_name='آپلود فایل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='document_flag',
            field=models.BooleanField(default=False, verbose_name='آپلود فایل'),
            preserve_default=False,
        ),
    ]
