# Generated by Django 5.1.6 on 2025-02-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='تلفن ثابت محل سکونت'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='postal_code',
            field=models.CharField(max_length=10, verbose_name='کد پستی محل سکونت'),
        ),
    ]
