# Generated by Django 5.1.6 on 2025-02-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_phone_alter_customuser_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='active_role',
            field=models.CharField(choices=[('br', 'پایه حقیقی'), ('bc', 'بازرگانی حقیقی / حقوقی'), ('it', 'تاجر حقیقی /حقوقی')], default='br', max_length=2, verbose_name='نقش فعال'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='base',
            field=models.BooleanField(default=True, verbose_name='پایه حقیقی'),
        ),
    ]
