# Generated by Django 5.1.6 on 2025-02-18 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_active_role_alter_customuser_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='verification_code',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)], verbose_name='کد تایید'),
        ),
    ]
