# Generated by Django 5.1.6 on 2025-02-19 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_verificationcode_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='active_role',
            field=models.CharField(choices=[('br', 'پایه حقیقی'), ('bc', 'بازرگان حقیقی'), ('it', 'تاجر حقیقی /حقوقی')], default='br', max_length=2, verbose_name='نقش فعال'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='has_business_card',
            field=models.BooleanField(default=False, verbose_name='بازرگان حقیقی'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='has_internal_trader',
            field=models.BooleanField(default=False, verbose_name='تاجر حقیقی'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='verification_code',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)], verbose_name='کد تایید'),
        ),
    ]
