# Generated by Django 5.1.6 on 2025-02-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_active_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='active_role',
            field=models.CharField(choices=[('br', 'پایه حقیقی- فعال'), ('bc', 'بازرگان حقیقی- فعال'), ('it', 'تاجر حقیقی /حقوقی')], default='br', max_length=2, verbose_name='نقش فعال'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
