# Generated by Django 5.1.6 on 2025-03-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_company_base',
            field=models.BooleanField(default=False, verbose_name='پایه حقوقی'),
        ),
    ]
