# Generated by Django 5.1.6 on 2025-03-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_has_company_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hass_company_business_card',
            field=models.BooleanField(default=False, verbose_name='نقش بازرگان حقوقی'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='active_role',
            field=models.CharField(choices=[('br', 'پایه حقیقی- فعال'), ('bt', 'پایه حقوقی- فعال'), ('bc', 'بازرگان حقیقی- فعال'), ('bl', 'بازرگان حقوقی- فعال'), ('it', 'تاجر حقیقی /حقوقی')], default='br', max_length=2, verbose_name='نقش فعال'),
        ),
    ]
