# Generated by Django 5.1.6 on 2025-03-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_hass_company_business_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='hass_company_business_card',
            field=models.BooleanField(default=False, verbose_name='بازرگان حقوقی'),
        ),
    ]
