# Generated by Django 5.1.6 on 2025-03-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_hass_company_business_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='hass_company_business_card',
            new_name='has_company_business_card',
        ),
    ]
