# Generated by Django 5.1.6 on 2025-04-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_hass_company_business_card_customuser_has_company_business_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verification_response',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='پیام درخواست نام و نام خانوادگی'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_response_result',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='نتیجه درخواست نام و نام خانوادگی'),
        ),
    ]
