# Generated by Django 5.1.5 on 2025-05-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_verification_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='نام\u200cخانوادگی'),
        ),
    ]
