# Generated by Django 5.1.5 on 2025-02-08 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('order_registration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maindata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='financial',
            name='main_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order_registration.maindata', verbose_name='داده\u200cهای اصلی'),
        ),
        migrations.AddField(
            model_name='customsandshipping',
            name='main_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_and_shipping', to='order_registration.maindata', verbose_name='داده\u200cهای اصلی'),
        ),
        migrations.AddField(
            model_name='maindata',
            name='order_registration_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order_registration.orderregistrationcase', verbose_name='حالت ثبت سفارش'),
        ),
        migrations.AddField(
            model_name='shippingtype',
            name='incoterms',
            field=models.ManyToManyField(related_name='incoterms', to='order_registration.incoterms', verbose_name='مرزهای ورودی'),
        ),
        migrations.AddField(
            model_name='entranceedge',
            name='shipping_type',
            field=models.ManyToManyField(to='order_registration.shippingtype', verbose_name='روش حمل'),
        ),
        migrations.AddField(
            model_name='customsandshipping',
            name='shipping_type',
            field=models.ManyToManyField(to='order_registration.shippingtype', verbose_name='روش\u200cهای حمل'),
        ),
        migrations.AddField(
            model_name='custom',
            name='shippint_type',
            field=models.ManyToManyField(to='order_registration.shippingtype', verbose_name='روش حمل'),
        ),
        migrations.AddField(
            model_name='ware',
            name='made_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.country', verbose_name='کشور تولید کننده'),
        ),
        migrations.AddField(
            model_name='ware',
            name='main_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_registration.maindata', verbose_name='اطلاعات اصلی'),
        ),
        migrations.AddField(
            model_name='ware',
            name='manufacture_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order_registration.manufactureyear', verbose_name='سال ساخت'),
        ),
        migrations.AddField(
            model_name='ware',
            name='packing_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order_registration.packing', verbose_name='نوع بسته بندی'),
        ),
    ]
