# Generated by Django 5.1.5 on 2025-02-08 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_registration', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custom',
            old_name='shippint_type',
            new_name='shipping_type',
        ),
    ]
