# Generated by Django 5.1.5 on 2025-02-08 09:49

import extensions.utils
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_registration', '0003_rename_shippint_type_custom_shipping_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='virtual_code',
            field=models.BigIntegerField(default=functools.partial(extensions.utils.generate_random_number, *(10,), **{}), verbose_name='کد مجازی'),
        ),
    ]
