# Generated by Django 5.1.5 on 2025-02-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_registration', '0004_alter_ware_virtual_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindata',
            name='registation_number',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='شماره ثبت سفارش'),
        ),
    ]
