# Generated by Django 5.1.5 on 2025-02-10 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_registration', '0005_alter_maindata_registation_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entranceedge',
            name='shipping_type',
        ),
    ]
