# Generated by Django 5.1.5 on 2025-02-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_registration', '0006_remove_entranceedge_shipping_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom',
            name='shipping_type',
        ),
        migrations.AddField(
            model_name='entranceedge',
            name='shipping_type',
            field=models.ManyToManyField(to='order_registration.shippingtype', verbose_name='روش حمل'),
        ),
    ]
