# Generated by Django 5.1.5 on 2025-02-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_registration', '0007_remove_custom_shipping_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencysupply',
            options={'ordering': ['order'], 'verbose_name': 'محل تامین ارز', 'verbose_name_plural': 'محل تامین ارز'},
        ),
        migrations.AddField(
            model_name='currencysupply',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='مرتب سازی'),
            preserve_default=False,
        ),
    ]
