# Generated by Django 5.1.5 on 2025-02-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_registration', '0008_alter_currencysupply_options_currencysupply_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial',
            name='other_price',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='سایر هزینه\u200cها'),
        ),
    ]
