# Generated by Django 5.1.5 on 2025-02-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_registration', '0009_alter_financial_other_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='organization_identifier',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='شناسه سازمان'),
        ),
        migrations.AlterField(
            model_name='ware',
            name='ware_identifier',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='شناسه کالا'),
        ),
    ]
