# Generated by Django 5.1.5 on 2025-02-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_registration', '0010_alter_ware_organization_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='off',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='تخفیف'),
        ),
    ]
