# Generated by Django 5.1.6 on 2025-02-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_registration', '0011_alter_ware_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindata',
            name='producer_type',
            field=models.CharField(choices=[('i', 'صنعتی (بهین یاب)'), ('g', 'صنفی'), ('m', 'معدنی'), ('a', 'کشاورزی'), ('e', 'وزارت نیرو')], max_length=1, verbose_name='نوع واحدهای تولیدی'),
        ),
        migrations.AlterField(
            model_name='ware',
            name='standard',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='استاندارد'),
        ),
        migrations.AlterField(
            model_name='ware',
            name='technical_specifications',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='مشخصات فنی'),
        ),
    ]
