# Generated by Django 5.1.6 on 2025-02-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_registration', '0012_alter_maindata_producer_type_alter_ware_standard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='تعداد/مقدار'),
        ),
        migrations.AlterField(
            model_name='ware',
            name='fob_price',
            field=models.PositiveIntegerField(verbose_name='مبلغ FOB'),
        ),
        migrations.AlterField(
            model_name='ware',
            name='gross_weight',
            field=models.PositiveIntegerField(verbose_name='وزن ناخالص(کیلوگرم)'),
        ),
        migrations.AlterField(
            model_name='ware',
            name='hs_code',
            field=models.PositiveIntegerField(verbose_name='شماره تعرفه'),
        ),
        migrations.AlterField(
            model_name='ware',
            name='net_weight',
            field=models.PositiveIntegerField(verbose_name='وزن خالص(کیلوگرم)'),
        ),
        migrations.AlterField(
            model_name='ware',
            name='off',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='ware',
            name='organization_identifier',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='شناسه سازمان'),
        ),
        migrations.AlterField(
            model_name='ware',
            name='ware_identifier',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='شناسه کالا'),
        ),
    ]
