# Generated by Django 5.1.6 on 2025-02-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_registration', '0013_alter_ware_amount_alter_ware_fob_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='amount',
            field=models.PositiveBigIntegerField(verbose_name='تعداد/مقدار'),
        ),
        migrations.AlterField(
            model_name='ware',
            name='fob_price',
            field=models.PositiveBigIntegerField(verbose_name='مبلغ FOB'),
        ),
    ]
