# Generated by Django 5.1.6 on 2025-02-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_registration', '0014_alter_ware_amount_alter_ware_fob_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderregistrationcase',
            options={'ordering': ['order_by'], 'verbose_name': 'حالت ثبت سفارش', 'verbose_name_plural': 'حالت ثبت سفارش'},
        ),
        migrations.AddField(
            model_name='orderregistrationcase',
            name='order_by',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='مرتب سازی'),
        ),
    ]
