# Generated by Django 5.1.6 on 2025-02-24 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_registration', '0015_alter_orderregistrationcase_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial',
            name='bank',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='order_registration.bank', verbose_name='بانک'),
        ),
        migrations.AlterField(
            model_name='financial',
            name='bank_branch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='order_registration.bankbranch', verbose_name='شعبه'),
        ),
    ]
