# Generated by Django 5.1.6 on 2025-02-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_registration', '0016_alter_financial_bank_alter_financial_bank_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
    ]
