# Generated by Django 5.1.6 on 2025-02-25 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_country_options'),
        ('order_registration', '0017_alter_custom_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packing',
            options={'ordering': ['order_by'], 'verbose_name': 'نوع بسته بندی', 'verbose_name_plural': 'نوع بسته بندی'},
        ),
        migrations.AddField(
            model_name='packing',
            name='order_by',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='مرتب سازی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bank',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='بانک'),
        ),
        migrations.AlterField(
            model_name='customsandshipping',
            name='origin_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.country', verbose_name='کشور مبدا حمل'),
        ),
        migrations.AlterField(
            model_name='packing',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان'),
        ),
    ]
