# Generated by Django 5.1.6 on 2025-02-25 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_registration', '0018_alter_packing_options_packing_order_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maindata',
            old_name='registation_number',
            new_name='registrations_number',
        ),
    ]
