# Generated by Django 5.1.6 on 2025-02-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_registration', '0019_rename_registation_number_maindata_registrations_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencysupply',
            name='currency_operation_type',
            field=models.CharField(choices=[('b', 'بانکی'), ('nb', 'بدون انتقال ارز')], default='b', max_length=2, verbose_name='نوع عملیات ارزی'),
        ),
    ]
