# Generated by Django 5.1.6 on 2025-02-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_registration', '0020_currencysupply_currency_operation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencysupply',
            name='title',
            field=models.CharField(max_length=300, verbose_name='عنوان'),
        ),
    ]
