# Generated by Django 5.1.6 on 2025-02-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_registration', '0021_alter_currencysupply_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial',
            name='proforma_amount',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='مبلغ کل پیش فاکتور'),
        ),
    ]
