# Generated by Django 5.1.6 on 2025-02-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_registration', '0022_alter_financial_proforma_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufactureyear',
            options={'ordering': ['order_by'], 'verbose_name': 'سال تولید', 'verbose_name_plural': 'سال تولید'},
        ),
        migrations.AddField(
            model_name='manufactureyear',
            name='order_by',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='مرتب سازی'),
        ),
    ]
