# Generated by Django 5.1.6 on 2025-03-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_registration', '0023_alter_manufactureyear_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='unit',
            field=models.CharField(choices=[('kg', 'کیلوگرم'), ('n', 'عدد'), ('m', 'متر'), ('s', 'ست'), ('mm', 'مترمربع'), ('mmm', 'مترمکعب'), ('l', 'لیتر'), ('p', 'جفت')], max_length=3, verbose_name='واحد اندازه گیری'),
        ),
    ]
