# Generated by Django 5.1.6 on 2025-03-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_registration', '0024_alter_ware_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial',
            name='off_amount',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='مبلغ تخفیف'),
        ),
    ]
