# Generated by Django 5.1.6 on 2025-03-03 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_registration', '0025_alter_financial_off_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maindata',
            options={'ordering': ['-created_at'], 'verbose_name': 'اطلاعات اصلی', 'verbose_name_plural': 'اطلاعات اصلی'},
        ),
    ]
