# Generated by Django 5.1.6 on 2025-03-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_registration', '0026_alter_maindata_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbranch',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
    ]
