# Generated by Django 5.1.6 on 2025-03-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_registration', '0027_alter_bankbranch_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial',
            name='off_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=22, null=True, verbose_name='مبلغ تخفیف'),
        ),
        migrations.AlterField(
            model_name='financial',
            name='other_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=22, null=True, verbose_name='سایر هزینه\u200cها'),
        ),
        migrations.AlterField(
            model_name='financial',
            name='proforma_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=22, null=True, verbose_name='مبلغ کل پیش فاکتور'),
        ),
        migrations.AlterField(
            model_name='financial',
            name='shipping_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=22, null=True, verbose_name='هزینه حمل'),
        ),
        migrations.AlterField(
            model_name='ware',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=22, verbose_name='تعداد/مقدار'),
        ),
        migrations.AlterField(
            model_name='ware',
            name='fob_price',
            field=models.DecimalField(decimal_places=2, max_digits=22, verbose_name='مبلغ FOB'),
        ),
        migrations.AlterField(
            model_name='ware',
            name='gross_weight',
            field=models.DecimalField(decimal_places=2, max_digits=22, verbose_name='وزن ناخالص(کیلوگرم)'),
        ),
        migrations.AlterField(
            model_name='ware',
            name='net_weight',
            field=models.DecimalField(decimal_places=2, max_digits=22, verbose_name='وزن خالص(کیلوگرم)'),
        ),
    ]
