# Generated by Django 5.1.5 on 2025-02-08 08:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='اپدیت شده در')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid کد')),
                ('fob_amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ فوب کالا')),
                ('shipping_price', models.PositiveIntegerField(verbose_name='مبلغ حمل')),
                ('inspection_amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ بازرسی')),
                ('off', models.PositiveIntegerField(default=0, verbose_name='تخفیف')),
                ('other_cost', models.PositiveIntegerField(default=0, verbose_name='سایر هزینه\u200cها')),
                ('total_price', models.PositiveIntegerField(verbose_name='مبلغ کل')),
                ('lading_bill_fob', models.PositiveIntegerField(verbose_name='مبلغ فوب سند حمل')),
                ('lading_bill_number', models.PositiveIntegerField(verbose_name='شماره بارنامه')),
                ('lading_bill_date', models.DateField(verbose_name='تاریخ بارنامه')),
                ('pay_number', models.PositiveIntegerField(verbose_name='شماره ابزار پرداخت')),
                ('shipping_document', models.CharField(max_length=50, verbose_name='انتخاب سند حمل')),
            ],
            options={
                'verbose_name': 'منشا ارز بانکی',
                'verbose_name_plural': 'منشا ارز بانکی',
            },
        ),
        migrations.CreateModel(
            name='LadingBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='اپدیت شده در')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid کد')),
                ('identifier', models.PositiveIntegerField(verbose_name='شماره بارنامه')),
                ('date', models.DateField(verbose_name='تاریخ بارنامه')),
            ],
            options={
                'verbose_name': 'بارنامه',
                'verbose_name_plural': 'بارنامه',
            },
        ),
        migrations.CreateModel(
            name='Ware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='اپدیت شده در')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid کد')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='تعداد/مقدار')),
                ('net_weight', models.PositiveSmallIntegerField(verbose_name='وزن خالص(کیلوگرم)')),
                ('gross_weight', models.PositiveSmallIntegerField(verbose_name='وزن ناخالص(کیلوگرم)')),
                ('packing_count', models.PositiveSmallIntegerField(verbose_name='تعداد بسته')),
            ],
            options={
                'verbose_name': 'کالاها',
            },
        ),
    ]
