# Generated by Django 5.1.5 on 2025-02-08 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currency_origin_determining', '0001_initial'),
        ('dashboard', '0001_initial'),
        ('order_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banking',
            name='custom_destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order_registration.custom', verbose_name='گمرک مقصد'),
        ),
        migrations.AddField(
            model_name='banking',
            name='entrance_edge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order_registration.entranceedge', verbose_name='مرز ورودی'),
        ),
        migrations.AddField(
            model_name='banking',
            name='main_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_registration.maindata', verbose_name='پرونده'),
        ),
        migrations.AddField(
            model_name='banking',
            name='origin_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.country', verbose_name='کشور مبدا حمل'),
        ),
    ]
