# Generated by Django 5.1.5 on 2025-02-08 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currency_origin_determining', '0002_initial'),
        ('order_registration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='banking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='ladingbill',
            name='banking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency_origin_determining.banking', verbose_name='منشا ارز بانکی'),
        ),
        migrations.AddField(
            model_name='ware',
            name='banking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency_origin_determining.banking', verbose_name=''),
        ),
        migrations.AddField(
            model_name='ware',
            name='order_registraiton_ware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_registration.ware', verbose_name='کالاهای منشا ارز'),
        ),
    ]
