# Generated by Django 5.1.5 on 2025-02-08 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency_origin_determining', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banking',
            name='lading_bill_date',
        ),
        migrations.RemoveField(
            model_name='banking',
            name='lading_bill_number',
        ),
    ]
