# Generated by Django 5.1.5 on 2025-02-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_origin_determining', '0004_remove_banking_lading_bill_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banking',
            name='shipping_price',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='مبلغ حمل'),
        ),
    ]
