# Generated by Django 5.1.5 on 2025-02-08 13:29

import extensions.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_origin_determining', '0005_alter_banking_shipping_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='banking',
            name='sata',
            field=models.CharField(default=extensions.utils.generate_sata_code, max_length=14, verbose_name='شماره ساتا'),
        ),
    ]
