# Generated by Django 5.1.5 on 2025-02-08 16:17

import extensions.utils
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_origin_determining', '0006_banking_sata'),
    ]

    operations = [
        migrations.AddField(
            model_name='banking',
            name='identifier',
            field=models.PositiveIntegerField(default=functools.partial(extensions.utils.generate_random_number, *(8,), **{}), verbose_name='کد یکتای منشا ارز'),
        ),
    ]
