# Generated by Django 5.1.5 on 2025-02-11 15:11

import django.db.models.deletion
import extensions.utils
import functools
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_origin_determining', '0007_banking_identifier'),
        ('dashboard', '0001_initial'),
        ('order_registration', '0007_remove_custom_shipping_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ware',
            options={'verbose_name': 'کالاها', 'verbose_name_plural': 'کالاها'},
        ),
        migrations.CreateModel(
            name='WithoutCurrencyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='اپدیت شده در')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid کد')),
                ('fob_amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ فوب کالا')),
                ('shipping_price', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='مبلغ حمل')),
                ('inspection_amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ بازرسی')),
                ('off', models.PositiveIntegerField(default=0, verbose_name='تخفیف')),
                ('other_cost', models.PositiveIntegerField(default=0, verbose_name='سایر هزینه\u200cها')),
                ('total_price', models.PositiveIntegerField(verbose_name='مبلغ کل')),
                ('lading_bill_fob', models.PositiveIntegerField(verbose_name='مبلغ فوب سند حمل')),
                ('pay_number', models.PositiveIntegerField(verbose_name='شماره ابزار پرداخت')),
                ('shipping_document', models.CharField(max_length=50, verbose_name='انتخاب سند حمل')),
                ('sata', models.CharField(default=extensions.utils.generate_sata_code, max_length=14, verbose_name='شماره ساتا')),
                ('identifier', models.PositiveIntegerField(default=functools.partial(extensions.utils.generate_random_number, *(8,), **{}), verbose_name='کد یکتای منشا ارز')),
                ('custom_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order_registration.custom', verbose_name='گمرک مقصد')),
                ('entrance_edge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order_registration.entranceedge', verbose_name='مرز ورودی')),
                ('main_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_registration.maindata', verbose_name='پرونده')),
                ('origin_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.country', verbose_name='کشور مبدا حمل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'منشا ارز بدون انتقال ارز',
                'verbose_name_plural': 'منشا ارز بدون انتقال ارز',
            },
        ),
        migrations.CreateModel(
            name='WithoutCurrencyTransferLadingBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='اپدیت شده در')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid کد')),
                ('identifier', models.PositiveIntegerField(verbose_name='شماره بارنامه')),
                ('date', models.DateField(verbose_name='تاریخ بارنامه')),
                ('without_currency_transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency_origin_determining.withoutcurrencytransfer', verbose_name='منشا ارز بدون انتقال ارز')),
            ],
            options={
                'verbose_name': 'بارنامه',
                'verbose_name_plural': 'بارنامه',
            },
        ),
        migrations.CreateModel(
            name='WithoutCurrencyTransferWare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='اپدیت شده در')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid کد')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='تعداد/مقدار')),
                ('net_weight', models.PositiveSmallIntegerField(verbose_name='وزن خالص(کیلوگرم)')),
                ('gross_weight', models.PositiveSmallIntegerField(verbose_name='وزن ناخالص(کیلوگرم)')),
                ('packing_count', models.PositiveSmallIntegerField(verbose_name='تعداد بسته')),
                ('order_registraiton_ware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_registration.ware', verbose_name='کالاهای منشا ارز')),
                ('without_currency_transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency_origin_determining.withoutcurrencytransfer', verbose_name='منشا ارز بدون انتقال ارز')),
            ],
            options={
                'verbose_name': 'کالاها',
                'verbose_name_plural': 'کالاها',
            },
        ),
    ]
