# Generated by Django 5.1.6 on 2025-02-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_origin_determining', '0008_alter_ware_options_withoutcurrencytransfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withoutcurrencytransferladingbill',
            name='tracking_code',
            field=models.CharField(default=1, max_length=50, verbose_name='کد رهگیری بارنامه'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='withoutcurrencytransferladingbill',
            name='date',
            field=models.DateField(verbose_name='تاریخ صدور بارنامه'),
        ),
    ]
