# Generated by Django 5.1.6 on 2025-03-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_origin_determining', '0009_withoutcurrencytransferladingbill_tracking_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banking',
            name='shipping_document',
            field=models.CharField(max_length=50, verbose_name='سند حمل را انتخاب کنید'),
        ),
        migrations.AlterField(
            model_name='withoutcurrencytransfer',
            name='shipping_document',
            field=models.CharField(max_length=50, verbose_name='سند حمل را انتخاب کنید'),
        ),
    ]
