# Generated by Django 5.1.6 on 2025-03-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_origin_determining', '0010_alter_banking_shipping_document_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banking',
            options={'ordering': ['-created_at'], 'verbose_name': 'منشا ارز بانکی', 'verbose_name_plural': 'منشا ارز بانکی'},
        ),
        migrations.AlterField(
            model_name='ladingbill',
            name='identifier',
            field=models.CharField(max_length=50, verbose_name='شماره بارنامه'),
        ),
        migrations.AlterField(
            model_name='withoutcurrencytransferladingbill',
            name='identifier',
            field=models.CharField(max_length=50, verbose_name='شماره بارنامه'),
        ),
    ]
