# Generated by Django 5.1.6 on 2025-03-05 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency_origin_determining', '0011_alter_banking_options_alter_ladingbill_identifier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withoutcurrencytransfer',
            options={'ordering': ['-created_at'], 'verbose_name': 'منشا ارز بدون انتقال ارز', 'verbose_name_plural': 'منشا ارز بدون انتقال ارز'},
        ),
    ]
