# Generated by Django 5.1.6 on 2025-03-05 09:54

import extensions.utils
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_origin_determining', '0012_alter_withoutcurrencytransfer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='banking',
            name='file_number',
            field=models.PositiveIntegerField(default=functools.partial(extensions.utils.generate_random_number, *(9,), **{}), verbose_name='شماره پرونده'),
        ),
    ]
