# Generated by Django 5.1.6 on 2025-03-05 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_origin_determining', '0013_banking_file_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ladingbill',
            name='banking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banking', to='currency_origin_determining.banking', verbose_name='منشا ارز بانکی'),
        ),
    ]
