# Generated by Django 5.1.6 on 2025-03-05 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_origin_determining', '0014_alter_ladingbill_banking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ladingbill',
            name='banking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilings', to='currency_origin_determining.banking', verbose_name='منشا ارز بانکی'),
        ),
        migrations.AlterField(
            model_name='ware',
            name='banking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wares', to='currency_origin_determining.banking', verbose_name='منشا ارز'),
        ),
    ]
