# Generated by Django 5.1.6 on 2025-03-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_origin_determining', '0015_alter_ladingbill_banking_alter_ware_banking'),
    ]

    operations = [
        migrations.AddField(
            model_name='banking',
            name='status',
            field=models.CharField(default='p', max_length=1, verbose_name='وضعیت'),
        ),
    ]
