# Generated by Django 5.1.6 on 2025-03-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_origin_determining', '0016_banking_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withoutcurrencytransferladingbill',
            options={'verbose_name': 'بارنامه بدون انتقال ارز', 'verbose_name_plural': 'بارنامه بدون انتقال ارز'},
        ),
        migrations.AlterModelOptions(
            name='withoutcurrencytransferware',
            options={'verbose_name': 'کالاهای بدون انتقال ارز', 'verbose_name_plural': 'کالاهای بدون انتقال ارز'},
        ),
        migrations.AlterField(
            model_name='banking',
            name='status',
            field=models.CharField(choices=[('p', 'ترخیص شده'), ('c', 'ابطال')], default='p', max_length=1, verbose_name='وضعیت'),
        ),
    ]
