# Generated by Django 5.1.6 on 2025-03-06 11:32

import extensions.utils
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_origin_determining', '0017_alter_withoutcurrencytransferladingbill_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withoutcurrencytransfer',
            name='file_number',
            field=models.PositiveIntegerField(default=functools.partial(extensions.utils.generate_random_number, *(9,), **{}), verbose_name='شماره پرونده'),
        ),
        migrations.AddField(
            model_name='withoutcurrencytransfer',
            name='status',
            field=models.CharField(choices=[('p', 'ترخیص شده'), ('c', 'ابطال')], default='p', max_length=1, verbose_name='وضعیت'),
        ),
    ]
