# Generated by Django 5.1.6 on 2025-03-06 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_origin_determining', '0018_withoutcurrencytransfer_file_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withoutcurrencytransferladingbill',
            name='without_currency_transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='currency_origin_determining.withoutcurrencytransfer', verbose_name='منشا ارز بدون انتقال ارز'),
        ),
        migrations.AlterField(
            model_name='withoutcurrencytransferware',
            name='without_currency_transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wares', to='currency_origin_determining.withoutcurrencytransfer', verbose_name='منشا ارز بدون انتقال ارز'),
        ),
    ]
