# Generated by Django 5.1.6 on 2025-03-06 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency_origin_determining', '0020_alter_withoutcurrencytransferladingbill_without_currency_transfer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banking',
            options={'ordering': ['-created_at', '-pk'], 'verbose_name': 'منشا ارز بانکی', 'verbose_name_plural': 'منشا ارز بانکی'},
        ),
        migrations.AlterModelOptions(
            name='withoutcurrencytransfer',
            options={'ordering': ['-created_at', '-pk'], 'verbose_name': 'منشا ارز بدون انتقال ارز', 'verbose_name_plural': 'منشا ارز بدون انتقال ارز'},
        ),
    ]
