# Generated by Django 5.1.6 on 2025-03-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_origin_determining', '0021_alter_banking_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banking',
            name='fob_amount',
            field=models.FloatField(default=0, verbose_name='مبلغ فوب کالا'),
        ),
        migrations.AlterField(
            model_name='banking',
            name='inspection_amount',
            field=models.FloatField(default=0, verbose_name='مبلغ بازرسی'),
        ),
        migrations.AlterField(
            model_name='banking',
            name='lading_bill_fob',
            field=models.FloatField(verbose_name='مبلغ فوب سند حمل'),
        ),
        migrations.AlterField(
            model_name='banking',
            name='off',
            field=models.FloatField(default=0, verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='banking',
            name='other_cost',
            field=models.FloatField(default=0, verbose_name='سایر هزینه\u200cها'),
        ),
        migrations.AlterField(
            model_name='banking',
            name='shipping_price',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='مبلغ حمل'),
        ),
        migrations.AlterField(
            model_name='ware',
            name='amount',
            field=models.FloatField(verbose_name='تعداد/مقدار'),
        ),
        migrations.AlterField(
            model_name='ware',
            name='gross_weight',
            field=models.FloatField(verbose_name='وزن ناخالص(کیلوگرم)'),
        ),
        migrations.AlterField(
            model_name='ware',
            name='net_weight',
            field=models.FloatField(verbose_name='وزن خالص(کیلوگرم)'),
        ),
        migrations.AlterField(
            model_name='ware',
            name='packing_count',
            field=models.FloatField(verbose_name='تعداد بسته'),
        ),
        migrations.AlterField(
            model_name='withoutcurrencytransfer',
            name='fob_amount',
            field=models.FloatField(default=0, verbose_name='مبلغ فوب کالا'),
        ),
        migrations.AlterField(
            model_name='withoutcurrencytransfer',
            name='inspection_amount',
            field=models.FloatField(default=0, verbose_name='مبلغ بازرسی'),
        ),
        migrations.AlterField(
            model_name='withoutcurrencytransfer',
            name='lading_bill_fob',
            field=models.FloatField(verbose_name='مبلغ فوب سند حمل'),
        ),
        migrations.AlterField(
            model_name='withoutcurrencytransfer',
            name='off',
            field=models.FloatField(default=0, verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='withoutcurrencytransfer',
            name='other_cost',
            field=models.FloatField(default=0, verbose_name='سایر هزینه\u200cها'),
        ),
        migrations.AlterField(
            model_name='withoutcurrencytransfer',
            name='shipping_price',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='مبلغ حمل'),
        ),
        migrations.AlterField(
            model_name='withoutcurrencytransfer',
            name='total_price',
            field=models.FloatField(verbose_name='مبلغ کل'),
        ),
        migrations.AlterField(
            model_name='withoutcurrencytransferware',
            name='amount',
            field=models.FloatField(verbose_name='تعداد/مقدار'),
        ),
        migrations.AlterField(
            model_name='withoutcurrencytransferware',
            name='gross_weight',
            field=models.FloatField(verbose_name='وزن ناخالص(کیلوگرم)'),
        ),
        migrations.AlterField(
            model_name='withoutcurrencytransferware',
            name='net_weight',
            field=models.FloatField(verbose_name='وزن خالص(کیلوگرم)'),
        ),
        migrations.AlterField(
            model_name='withoutcurrencytransferware',
            name='packing_count',
            field=models.FloatField(verbose_name='تعداد بسته'),
        ),
    ]
