# Generated by Django 5.1.6 on 2025-03-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_origin_determining', '0022_alter_banking_fob_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banking',
            name='status',
            field=models.CharField(choices=[('p', 'ترخیص شده'), ('c', 'ابطال'), ('r', 'اماده اظهار گمرکی')], default='r', max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='banking',
            name='total_price',
            field=models.FloatField(verbose_name='مبلغ کل'),
        ),
        migrations.AlterField(
            model_name='withoutcurrencytransfer',
            name='status',
            field=models.CharField(choices=[('p', 'ترخیص شده'), ('c', 'ابطال'), ('r', 'اماده اظهار گمرکی')], default='r', max_length=1, verbose_name='وضعیت'),
        ),
    ]
