# Generated by Django 5.1.5 on 2025-02-13 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'کشور', 'verbose_name_plural': 'کشور'},
        ),
    ]
