# Generated by Django 5.1.5 on 2025-05-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ref_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
