# Generated by Django 5.1.5 on 2025-02-08 08:31

import django.db.models.deletion
import extensions.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='اپدیت شده در')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid کد')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'نرخ ارز',
                'verbose_name_plural': 'نرخ ارز',
            },
        ),
        migrations.CreateModel(
            name='FacilityLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='اپدیت شده در')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid کد')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'محل تسهیلات',
                'verbose_name_plural': 'محل تسهیلات',
            },
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='اپدیت شده در')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid کد')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'نوع درخواست',
                'verbose_name_plural': 'نوع درخواست',
            },
        ),
        migrations.CreateModel(
            name='SupplyCurrencyPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='اپدیت شده در')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid کد')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'محل تامین ارز',
                'verbose_name_plural': 'محل تامین ارز',
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='اپدیت شده در')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid کد')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'نوع معامله',
                'verbose_name_plural': 'نوع معامله',
            },
        ),
        migrations.CreateModel(
            name='Undertaking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='اپدیت شده در')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid کد')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'متعهد',
                'verbose_name_plural': 'متعهد',
            },
        ),
        migrations.CreateModel(
            name='RepaymentDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='اپدیت شده در')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid کد')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('facility_location', models.ManyToManyField(to='currency_allocation.facilitylocation', verbose_name='محل تسهیلات')),
            ],
            options={
                'verbose_name': 'مهلت بازپرداخت',
                'verbose_name_plural': 'مهلت بازپرداخت',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='اپدیت شده در')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid کد')),
                ('request_amount_by_main_data_currency', models.PositiveIntegerField(verbose_name='مبلغ درخواست به ارز ثبت سفارش')),
                ('request_amount', models.PositiveIntegerField(verbose_name='مبلغ در خواست')),
                ('duration_per_month', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='مدت به ماه')),
                ('expire_date', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='مهلت انقضا')),
                ('document', models.FileField(blank=True, default=None, max_length=500, null=True, upload_to='currency_allocation/request/', validators=[extensions.validators.validate_file_size, extensions.validators.validate_file_extension], verbose_name='مستندات پروند')),
                ('row', models.CharField(default='2', max_length=1, verbose_name='ردیف درخواست')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.currency', verbose_name='ارز درخواستی')),
                ('currency_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currency_allocation.currencyrate', verbose_name='نرخ ارز')),
                ('facility_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currency_allocation.facilitylocation', verbose_name='محل تسهیلات')),
            ],
            options={
                'verbose_name': 'درخواست تخصیص ارز',
                'verbose_name_plural': 'درخواست تخصیص ارز',
            },
        ),
    ]
