# Generated by Django 5.1.5 on 2025-02-08 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currency_allocation', '0001_initial'),
        ('order_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='main_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order_registration.maindata', verbose_name='پرونده ثبت سفارش'),
        ),
        migrations.AddField(
            model_name='request',
            name='repayment_deadline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currency_allocation.repaymentdeadline', verbose_name='مهلت باز پرداخت'),
        ),
        migrations.AddField(
            model_name='requesttype',
            name='currency_rate',
            field=models.ManyToManyField(to='currency_allocation.currencyrate', verbose_name='نرخ ارز'),
        ),
        migrations.AddField(
            model_name='request',
            name='request_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currency_allocation.requesttype', verbose_name='نوع درخواست'),
        ),
        migrations.AddField(
            model_name='supplycurrencyplace',
            name='repayment_deadline',
            field=models.ManyToManyField(to='currency_allocation.repaymentdeadline', verbose_name='محل بازپرداخت'),
        ),
        migrations.AddField(
            model_name='request',
            name='supply_currency_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currency_allocation.supplycurrencyplace', verbose_name='محل تامین ارز'),
        ),
        migrations.AddField(
            model_name='currencyrate',
            name='supply_currency',
            field=models.ManyToManyField(to='currency_allocation.supplycurrencyplace', verbose_name='محل تامین ارز'),
        ),
        migrations.AddField(
            model_name='request',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currency_allocation.transactiontype', verbose_name='نوع معامله'),
        ),
        migrations.AddField(
            model_name='undertaking',
            name='transaction_type',
            field=models.ManyToManyField(to='currency_allocation.transactiontype', verbose_name='نوع معامله'),
        ),
        migrations.AddField(
            model_name='request',
            name='undertaking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currency_allocation.undertaking', verbose_name='متعهد'),
        ),
        migrations.AddField(
            model_name='facilitylocation',
            name='undertaking',
            field=models.ManyToManyField(to='currency_allocation.undertaking', verbose_name='متعهد'),
        ),
    ]
