# Generated by Django 5.1.5 on 2025-02-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_allocation', '0004_alter_request_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='row',
            field=models.CharField(default='1', max_length=1, verbose_name='ردیف درخواست'),
        ),
    ]
