# Generated by Django 5.1.6 on 2025-02-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_allocation', '0015_alter_request_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='row',
            field=models.CharField(default='2', max_length=1, verbose_name='ردیف درخواست'),
        ),
    ]
