# Generated by Django 5.1.6 on 2025-02-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_allocation', '0019_alter_request_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitylocation',
            name='transaction_type',
            field=models.ManyToManyField(to='currency_allocation.transactiontype', verbose_name='نوع معامله'),
        ),
        migrations.AddField(
            model_name='supplycurrencyplace',
            name='facility_location',
            field=models.ManyToManyField(to='currency_allocation.facilitylocation', verbose_name='محل تسهیلات'),
        ),
    ]
