# Generated by Django 5.1.6 on 2025-02-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_allocation', '0020_facilitylocation_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyrate',
            name='facility_location',
            field=models.ManyToManyField(to='currency_allocation.facilitylocation', verbose_name='محل تسهیلات'),
        ),
        migrations.AddField(
            model_name='currencyrate',
            name='repayment_deadline',
            field=models.ManyToManyField(to='currency_allocation.repaymentdeadline', verbose_name='مهلت بازپرداخت'),
        ),
        migrations.AddField(
            model_name='currencyrate',
            name='transaction_type',
            field=models.ManyToManyField(to='currency_allocation.transactiontype', verbose_name='نوع معامله'),
        ),
        migrations.AddField(
            model_name='currencyrate',
            name='undertaking',
            field=models.ManyToManyField(to='currency_allocation.undertaking', verbose_name='متعهد'),
        ),
        migrations.AddField(
            model_name='repaymentdeadline',
            name='transaction_type',
            field=models.ManyToManyField(to='currency_allocation.transactiontype', verbose_name='نوع معامله'),
        ),
        migrations.AddField(
            model_name='repaymentdeadline',
            name='undertaking',
            field=models.ManyToManyField(to='currency_allocation.undertaking', verbose_name='متعهد'),
        ),
        migrations.AddField(
            model_name='requesttype',
            name='facility_location',
            field=models.ManyToManyField(to='currency_allocation.facilitylocation', verbose_name='محل تسهیلات'),
        ),
        migrations.AddField(
            model_name='requesttype',
            name='repayment_deadline',
            field=models.ManyToManyField(to='currency_allocation.repaymentdeadline', verbose_name='مهلت بازپرداخت'),
        ),
        migrations.AddField(
            model_name='requesttype',
            name='supply_currency',
            field=models.ManyToManyField(to='currency_allocation.supplycurrencyplace', verbose_name='محل تامین ارز'),
        ),
        migrations.AddField(
            model_name='requesttype',
            name='transaction_type',
            field=models.ManyToManyField(to='currency_allocation.transactiontype', verbose_name='نوع معامله'),
        ),
        migrations.AddField(
            model_name='requesttype',
            name='undertaking',
            field=models.ManyToManyField(to='currency_allocation.undertaking', verbose_name='متعهد'),
        ),
        migrations.AddField(
            model_name='supplycurrencyplace',
            name='transaction_type',
            field=models.ManyToManyField(to='currency_allocation.transactiontype', verbose_name='نوع معامله'),
        ),
        migrations.AddField(
            model_name='supplycurrencyplace',
            name='undertaking',
            field=models.ManyToManyField(to='currency_allocation.undertaking', verbose_name='متعهد'),
        ),
        migrations.AlterField(
            model_name='request',
            name='row',
            field=models.CharField(default='2', max_length=1, verbose_name='ردیف درخواست'),
        ),
        migrations.AlterField(
            model_name='supplycurrencyplace',
            name='repayment_deadline',
            field=models.ManyToManyField(to='currency_allocation.repaymentdeadline', verbose_name='مهلت بازپرداخت'),
        ),
    ]
