# Generated by Django 5.1.6 on 2025-02-23 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_allocation', '0021_currencyrate_facility_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencyrate',
            name='facility_location',
        ),
        migrations.RemoveField(
            model_name='currencyrate',
            name='repayment_deadline',
        ),
        migrations.RemoveField(
            model_name='currencyrate',
            name='supply_currency',
        ),
        migrations.RemoveField(
            model_name='currencyrate',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='currencyrate',
            name='undertaking',
        ),
        migrations.RemoveField(
            model_name='facilitylocation',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='facilitylocation',
            name='undertaking',
        ),
        migrations.RemoveField(
            model_name='repaymentdeadline',
            name='facility_location',
        ),
        migrations.RemoveField(
            model_name='repaymentdeadline',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='repaymentdeadline',
            name='undertaking',
        ),
        migrations.AlterField(
            model_name='request',
            name='row',
            field=models.CharField(default='1', max_length=1, verbose_name='ردیف درخواست'),
        ),
        migrations.RemoveField(
            model_name='requesttype',
            name='currency_rate',
        ),
        migrations.RemoveField(
            model_name='requesttype',
            name='facility_location',
        ),
        migrations.RemoveField(
            model_name='requesttype',
            name='repayment_deadline',
        ),
        migrations.RemoveField(
            model_name='requesttype',
            name='supply_currency',
        ),
        migrations.RemoveField(
            model_name='requesttype',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='requesttype',
            name='undertaking',
        ),
        migrations.RemoveField(
            model_name='supplycurrencyplace',
            name='facility_location',
        ),
        migrations.RemoveField(
            model_name='supplycurrencyplace',
            name='repayment_deadline',
        ),
        migrations.RemoveField(
            model_name='supplycurrencyplace',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='supplycurrencyplace',
            name='undertaking',
        ),
        migrations.RemoveField(
            model_name='undertaking',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='currencyrate',
            name='facility_location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='currency_allocation.facilitylocation', verbose_name='محل تسهیلات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currencyrate',
            name='repayment_deadline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currency_allocation.repaymentdeadline', verbose_name='مهلت بازپرداخت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currencyrate',
            name='supply_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currency_allocation.supplycurrencyplace', verbose_name='محل تامین ارز'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currencyrate',
            name='transaction_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currency_allocation.transactiontype', verbose_name='نوع معامله'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currencyrate',
            name='undertaking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currency_allocation.undertaking', verbose_name='متعهد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facilitylocation',
            name='transaction_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currency_allocation.transactiontype', verbose_name='نوع معامله'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facilitylocation',
            name='undertaking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currency_allocation.undertaking', verbose_name='متعهد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repaymentdeadline',
            name='facility_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currency_allocation.facilitylocation', verbose_name='محل تسهیلات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repaymentdeadline',
            name='transaction_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currency_allocation.transactiontype', verbose_name='نوع معامله'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repaymentdeadline',
            name='undertaking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currency_allocation.undertaking', verbose_name='متعهد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requesttype',
            name='currency_rate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currency_allocation.currencyrate', verbose_name='نرخ ارز'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requesttype',
            name='facility_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currency_allocation.facilitylocation', verbose_name='محل تسهیلات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requesttype',
            name='repayment_deadline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currency_allocation.repaymentdeadline', verbose_name='مهلت بازپرداخت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requesttype',
            name='supply_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currency_allocation.supplycurrencyplace', verbose_name='محل تامین ارز'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requesttype',
            name='transaction_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currency_allocation.transactiontype', verbose_name='نوع معامله'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requesttype',
            name='undertaking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currency_allocation.undertaking', verbose_name='متعهد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplycurrencyplace',
            name='facility_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currency_allocation.facilitylocation', verbose_name='محل تسهیلات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplycurrencyplace',
            name='repayment_deadline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currency_allocation.repaymentdeadline', verbose_name='مهلت بازپرداخت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplycurrencyplace',
            name='transaction_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currency_allocation.transactiontype', verbose_name='نوع معامله'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplycurrencyplace',
            name='undertaking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currency_allocation.undertaking', verbose_name='متعهد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='undertaking',
            name='transaction_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currency_allocation.transactiontype', verbose_name='نوع معامله'),
            preserve_default=False,
        ),
    ]
