# Generated by Django 5.1.6 on 2025-02-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_allocation', '0022_remove_currencyrate_facility_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencyrate',
            name='facility_location',
        ),
        migrations.RemoveField(
            model_name='currencyrate',
            name='repayment_deadline',
        ),
        migrations.RemoveField(
            model_name='currencyrate',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='currencyrate',
            name='undertaking',
        ),
        migrations.RemoveField(
            model_name='facilitylocation',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='repaymentdeadline',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='repaymentdeadline',
            name='undertaking',
        ),
        migrations.RemoveField(
            model_name='requesttype',
            name='facility_location',
        ),
        migrations.RemoveField(
            model_name='requesttype',
            name='repayment_deadline',
        ),
        migrations.RemoveField(
            model_name='requesttype',
            name='supply_currency',
        ),
        migrations.RemoveField(
            model_name='requesttype',
            name='undertaking',
        ),
        migrations.RemoveField(
            model_name='supplycurrencyplace',
            name='facility_location',
        ),
        migrations.RemoveField(
            model_name='supplycurrencyplace',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='supplycurrencyplace',
            name='undertaking',
        ),
        migrations.AlterField(
            model_name='request',
            name='row',
            field=models.CharField(default='2', max_length=1, verbose_name='ردیف درخواست'),
        ),
    ]
