# Generated by Django 5.1.6 on 2025-02-23 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency_allocation', '0023_remove_currencyrate_facility_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesttype',
            name='currency_rate',
        ),
    ]
