# Generated by Django 5.1.6 on 2025-02-23 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_allocation', '0024_remove_requesttype_currency_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesttype',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='requesttype',
            name='currency_rate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currency_allocation.currencyrate', verbose_name='نرخ ارز'),
            preserve_default=False,
        ),
    ]
