# Generated by Django 5.1.6 on 2025-02-25 22:20

import django.db.models.deletion
import extensions.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_allocation', '0031_alter_request_row'),
        ('dashboard', '0002_alter_country_options'),
        ('order_registration', '0023_alter_manufactureyear_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='اپدیت شده در')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid کد')),
                ('request_amount_by_main_data_currency', models.PositiveIntegerField(verbose_name='مبلغ درخواست به ارز ثبت سفارش')),
                ('request_amount', models.PositiveIntegerField(verbose_name='مبلغ در خواست')),
                ('duration_per_month', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='مدت به ماه')),
                ('expire_date', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='مهلت انقضا')),
                ('document', models.FileField(blank=True, default=None, max_length=500, null=True, upload_to='currency_allocation/request/', validators=[extensions.validators.validate_file_size, extensions.validators.validate_file_extension], verbose_name='مستندات پروند')),
                ('row', models.CharField(default='1', max_length=1, verbose_name='ردیف درخواست')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.currency', verbose_name='ارز درخواستی')),
                ('currency_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currency_allocation.currencyrate', verbose_name='نرخ ارز')),
                ('facility_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currency_allocation.facilitylocation', verbose_name='محل تسهیلات')),
                ('main_data', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order_registration.maindata', verbose_name='پرونده ثبت سفارش')),
                ('repayment_deadline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currency_allocation.repaymentdeadline', verbose_name='مهلت باز پرداخت')),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currency_allocation.requesttype', verbose_name='نوع درخواست')),
                ('supply_currency_place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currency_allocation.supplycurrencyplace', verbose_name='محل تامین ارز')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currency_allocation.transactiontype', verbose_name='نوع معامله')),
                ('undertaking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currency_allocation.undertaking', verbose_name='متعهد')),
            ],
            options={
                'verbose_name': 'درخواست تخصیص ارز',
                'verbose_name_plural': 'درخواست تخصیص ارز',
            },
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
