# Generated by Django 5.1.6 on 2025-03-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_allocation', '0032_currencyrequest_delete_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrequest',
            name='duration_per_month',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='مدت به ماه (حداکثر ۰ ماه)'),
        ),
        migrations.AlterField(
            model_name='currencyrequest',
            name='expire_date',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='مهلت انقضا(حداکثر تا ۴۵ روز)'),
        ),
    ]
