# Generated by Django 5.1.6 on 2025-03-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_allocation', '0033_alter_currencyrequest_duration_per_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyrequest',
            name='status',
            field=models.CharField(choices=[('c', '\u200cابطال'), ('a', 'تخصیص یافته')], default='a', max_length=50, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='currencyrequest',
            name='row',
            field=models.CharField(default='2', max_length=1, verbose_name='ردیف درخواست'),
        ),
    ]
