# Generated by Django 5.1.6 on 2025-03-02 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_allocation', '0034_currencyrequest_status_alter_currencyrequest_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyrequest',
            name='parent_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='currency_allocation.currencyrequest', verbose_name='درخواست تخصیص'),
        ),
        migrations.AlterField(
            model_name='currencyrequest',
            name='row',
            field=models.CharField(default='1', max_length=1, verbose_name='ردیف درخواست'),
        ),
    ]
