# Generated by Django 5.1.6 on 2025-03-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_allocation', '0035_currencyrequest_parent_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrequest',
            name='row',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='ردیف'),
        ),
    ]
