# Generated by Django 5.1.6 on 2025-03-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_allocation', '0036_alter_currencyrequest_row'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencyrequest',
            options={'ordering': ['-created_at', '-row'], 'verbose_name': 'درخواست تخصیص ارز', 'verbose_name_plural': 'درخواست تخصیص ارز'},
        ),
        migrations.AlterField(
            model_name='currencyrequest',
            name='request_amount',
            field=models.FloatField(verbose_name='مبلغ در خواست'),
        ),
        migrations.AlterField(
            model_name='currencyrequest',
            name='request_amount_by_main_data_currency',
            field=models.FloatField(verbose_name='مبلغ درخواست به ارز ثبت سفارش'),
        ),
    ]
