# Generated by Django 5.1.6 on 2025-03-02 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_allocation', '0038_alter_currencyrequest_parent_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrequest',
            name='parent_request',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='currency_allocation.currencyrequest', verbose_name='درخواست تخصیص'),
        ),
    ]
