# Generated by Django 5.1.6 on 2025-03-06 18:09

import extensions.utils
import extensions.validators
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_allocation', '0039_alter_currencyrequest_parent_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyrequest',
            name='file_number',
            field=models.PositiveIntegerField(default=functools.partial(extensions.utils.generate_random_number, *(9,), **{}), verbose_name='شماره پرونده'),
        ),
        migrations.AlterField(
            model_name='currencyrequest',
            name='document',
            field=models.FileField(blank=True, default=None, max_length=500, null=True, upload_to='currency_allocation/request/', validators=[extensions.validators.validate_file_size, extensions.validators.validate_file_extension], verbose_name='مستندات پرونده'),
        ),
    ]
