# Generated by Django 5.1.6 on 2025-03-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_allocation', '0041_currencyrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyrequest',
            name='request_update',
            field=models.BooleanField(default=False, verbose_name='درخواست ویرایش دارد'),
        ),
    ]
