# Generated by Django 5.1.6 on 2025-03-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_allocation', '0042_currencyrequest_request_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrequest',
            name='request_update',
            field=models.BooleanField(default=False, verbose_name='درخواست تمدید دارد'),
        ),
    ]
