# Generated by Django 5.1.6 on 2025-04-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_allocation', '0043_alter_currencyrequest_request_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrequest',
            name='duration_per_month',
            field=models.PositiveIntegerField(default=0, verbose_name='مدت به ماه (حداکثر ۰ ماه)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currencyrequest',
            name='expire_date',
            field=models.PositiveIntegerField(default=0, verbose_name='مهلت انقضا(حداکثر تا ۴۵ روز)'),
            preserve_default=False,
        ),
    ]
