# Generated by Django 5.1.5 on 2025-02-08 08:31

import upload_qualifications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.PositiveIntegerField(default=upload_qualifications.models.generate_random_number, verbose_name='شماره درخواست')),
                ('request_type', models.CharField(default='صدور', max_length=50, verbose_name='نوع درخواست')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('status', models.CharField(choices=[('FC', 'تایید نهایی')], default='FC', max_length=5, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'کارت بازرگانی',
                'verbose_name_plural': 'کارت\u200cهای بازرگانی',
            },
        ),
    ]
