# Generated by Django 5.1.6 on 2025-03-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_qualifications', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_type', models.CharField(choices=[('g', 'دولتی'), ('p', 'خصوصی')], max_length=1, verbose_name='نوع مالکیت شرکت')),
                ('national_identifier', models.CharField(max_length=11, verbose_name='شناسه ملی شرکت')),
                ('email', models.EmailField(max_length=254, verbose_name='پست الکترونیک شخصیت حقوقی')),
                ('url', models.URLField(blank=True, default=None, verbose_name='پایگاه اینترنتی شخصیت حقوقی')),
                ('fax', models.CharField(max_length=11, verbose_name='نمابر شخصیت حقوقی')),
                ('phone', models.CharField(max_length=11, verbose_name='تلفن ثابت شخصیت حقوقی')),
            ],
            options={
                'verbose_name': 'بازرگان حقیقی',
                'verbose_name_plural': 'بازرگان حقیقی',
            },
        ),
    ]
