# Generated by Django 5.1.6 on 2025-03-08 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_qualifications', '0003_companybase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companybase',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companybase',
            name='url',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='پایگاه اینترنتی شخصیت حقوقی'),
        ),
    ]
