# Generated by Django 5.1.6 on 2025-03-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_qualifications', '0005_alter_companybase_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscard',
            name='card_type',
            field=models.CharField(choices=[('p', 'حقیقی'), ('c', 'حقوقی')], default='p', max_length=1, verbose_name='نوع'),
        ),
    ]
