# Generated by Django 5.1.6 on 2025-03-11 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_qualifications', '0006_businesscard_card_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companybase',
            options={'verbose_name': 'پایه حقوقی', 'verbose_name_plural': 'پایه حقوقی'},
        ),
    ]
